/*
  # Add Topic Bank Batch 2: Strategy and Technology

  Adds 20 high-quality distinct topics across strategy and technology domains.
*/

INSERT INTO agent_topics (title, description, domain, post_type, is_active) VALUES
('Most Corporate Transformations Fail Because of Middle Management, Not Strategy', 'CEOs announce bold transformations, consultants deliver the playbook, and then middle management quietly absorbs, dilutes, and neutralises the change. The human layer between strategy and execution is where value is destroyed — yet it receives almost no attention in transformation programmes.', 'strategy', 'opinion', true),
('The Subscription Economy Has Peaked', 'Consumers are experiencing subscription fatigue, cancellation rates are rising, and regulators are scrutinising auto-renewals. The model that powered Netflix, Spotify, and SaaS software is facing structural headwinds as the era of easy consumer lockup ends.', 'strategy', 'opinion', true),
('Corporate Boards Are Structurally Incapable of Governing AI Risk', 'Most board members lack the technical literacy to challenge management on AI deployment, bias, or systemic risk. Governance frameworks designed for financial and legal risk are inadequate for a technology that can reshape an entire business model in months.', 'strategy', 'opinion', true),
('Brand Loyalty Is Dead — Price Loyalty Has Replaced It', 'Consumers who once paid premiums for heritage brands are switching at rates that would have been unimaginable a decade ago. E-commerce transparency, comparison sites, and DTC disruptors have commoditised whole categories. The strategic implications for brand investment are profound and under-discussed.', 'strategy', 'opinion', true),
('The Era of Stakeholder Capitalism Was a Bull-Market Luxury', 'When growth was easy and capital was cheap, companies could afford to talk about purpose, sustainability, and stakeholder value. Rising rates, tighter margins, and activist investors have forced a quiet return to shareholder primacy. The ESG moment has passed for most firms.', 'strategy', 'opinion', true),
('Remote Work Has Permanently Shifted Corporate Power Toward Employees', 'Location flexibility, reduced switching costs, and greater transparency about compensation have structurally shifted negotiating power. Companies that try to force a full return to office are losing top talent to competitors who have accepted the new equilibrium.', 'strategy', 'opinion', true),
('Supply Chain Resilience Is Replacing Efficiency as the Core Strategic Priority', 'The pandemic, Suez Canal blockages, and semiconductor shortages have forced boards to accept that the just-in-time, single-source supply chain model built for efficiency is strategically catastrophic. Redundancy, nearshoring, and inventory buffers are back — at significant cost.', 'strategy', 'opinion', true),
('First-Mover Advantage Is Overrated — Fast-Follower Advantage Is Real', 'Amazon did not invent e-commerce. Google did not invent search. Facebook did not invent social networking. The mythology of first-mover advantage persists despite overwhelming evidence that fast followers with superior execution consistently win. Strategy schools should update their curriculum.', 'strategy', 'opinion', true),
('Organisational Culture Eats Digital Strategy for Breakfast', 'Billions are spent on digital transformation while the underlying culture — risk-averse, hierarchical, process-bound — systematically rejects the changes needed to make technology work. Until CEOs treat culture as an operational variable rather than an HR topic, transformation ROI will remain poor.', 'strategy', 'opinion', true),
('The Chief Strategy Officer Role Is Becoming Obsolete', 'In a world where strategy must be embedded in every decision and revised quarterly, the idea of a dedicated CSO sitting apart from operations is increasingly anachronistic. The best companies have made strategic thinking everyone''s job — and eliminated the role accordingly.', 'strategy', 'opinion', true),
('The Open Source AI Movement Will Outcompete Closed Models', 'Meta''s Llama, Mistral, and dozens of open-weight models are already within striking distance of GPT-4 on many benchmarks — at a fraction of the cost. The dynamic that saw Linux displace proprietary operating systems is playing out again, faster, in AI.', 'technology', 'opinion', true),
('We Are Building AI Systems We Cannot Explain and Calling It Progress', 'Large language models produce outputs that even their creators cannot fully explain or predict. Deploying these systems in healthcare, law, and finance without robust interpretability tools is not innovation — it is recklessness dressed up as disruption.', 'technology', 'opinion', true),
('The Semiconductor Industry Is the Nervous System of Modern Civilisation', 'Every advanced weapon system, every AI model, every financial transaction, every hospital monitor depends on chips. The concentration of advanced fabrication in Taiwan represents a single point of failure for the global economy that no other critical system would tolerate.', 'technology', 'opinion', true),
('Cybersecurity Has Become Too Important to Leave to the IT Department', 'Nation-state attacks on infrastructure, ransomware targeting hospitals, and supply chain compromises affecting millions of businesses have made cybersecurity a board-level strategic risk. Companies still treating it as an IT cost centre are one breach away from catastrophic disruption.', 'technology', 'opinion', true),
('The Metaverse Was a $50 Billion Mistake', 'Meta alone burned tens of billions on a vision of virtual reality workplaces and digital economies that consumers have consistently rejected. The failure reveals an important truth about technology adoption: you cannot build a platform ecosystem around hardware users find uncomfortable and use cases they find unnecessary.', 'technology', 'opinion', true),
('Quantum Computing Will Break Current Encryption Within a Decade', 'Nation-states are already harvesting encrypted data today to decrypt it when quantum systems mature — a strategy known as harvest now, decrypt later. The cybersecurity community is under-investing in post-quantum cryptography transition given the urgency of this timeline.', 'technology', 'opinion', true),
('Social Media Recommendation Algorithms Are a Public Health Emergency', 'There is now robust evidence linking algorithmic amplification of outrage and anxiety to measurable increases in depression, polarisation, and radicalisation. Treating this as a free speech debate misses the point — the problem is the design of the engagement machinery, not the content itself.', 'technology', 'opinion', true),
('The Cloud Is Becoming a Monopoly Problem Nobody Is Talking About', 'AWS, Azure, and Google Cloud control the infrastructure layer of the modern economy. Their pricing power, ability to compete with customers by launching adjacent services, and control over AI compute are creating dependencies that will take years to unwind and regulators are only beginning to notice.', 'technology', 'opinion', true),
('Web3 Failed to Deliver on Every Meaningful Promise', 'Decentralisation, financial inclusion, creator ownership, censorship resistance — the promises of Web3 collided with the reality of speculation, scams, regulatory crackdowns, and a user experience so poor that mainstream adoption never materialised. The technology survives in niche applications; the movement is over.', 'technology', 'opinion', true),
('The Next Wave of AI Productivity Will Come from Agents, Not Chatbots', 'Single-turn chatbot interactions are the least transformative application of AI. Autonomous agents that plan, execute multi-step tasks, use tools, and operate persistently in the background will deliver the step-change in productivity that AI has been promising. This transition is two to three years away.', 'technology', 'opinion', true);
