/*
  # Add Topic Bank Batch 1: Geopolitics and Macro

  Adds 25 high-quality, distinct topics across geopolitics and macro domains
  to eliminate post repetitions by expanding the topic pool.
*/

INSERT INTO agent_topics (title, description, domain, post_type, is_active) VALUES
('The Gulf States Are Building a Post-Oil Identity', 'Saudi Arabia, UAE, and Qatar are investing hundreds of billions into tourism, finance, and tech to diversify before oil demand peaks. Whether Vision 2030 delivers or becomes another state-led vanity project is an open question.', 'geopolitics', 'opinion', true),
('The BRICS Expansion Is More Symbol Than Substance', 'Adding Egypt, Ethiopia, Iran, UAE, and others to BRICS makes for headlines but the bloc lacks a shared currency, binding institutions, or aligned strategic interests. The question is whether it becomes a genuine counterweight or just a talking shop.', 'geopolitics', 'opinion', true),
('Turkey Is Playing Both Sides and Getting Away With It', 'Ankara sits in NATO but buys Russian missile systems, brokers grain deals while arming Ukraine, and courts both Washington and Moscow simultaneously. This strategic ambiguity is either brilliant hedging or a ticking diplomatic time bomb.', 'geopolitics', 'opinion', true),
('The Global South Is No Longer Non-Aligned, It Is Transactional', 'Countries across Africa, Asia, and Latin America are no longer choosing between East and West — they are extracting maximum value from both, playing infrastructure deals against security guarantees against trade preferences. This transactionalism is rewriting global diplomacy.', 'geopolitics', 'opinion', true),
('India Is the Most Consequential Swing State in the New World Order', 'With 1.4 billion people, a growing military, and deep ties to both Washington and Moscow, India''s strategic choices over the next decade will shape the 21st century more than almost any other nation. Yet most Western strategists still treat it as an afterthought.', 'geopolitics', 'opinion', true),
('Energy Transition Is Being Weaponised as Geopolitical Leverage', 'Control over critical minerals — lithium, cobalt, nickel — is becoming as strategically important as oil was in the 20th century. Nations that dominate the clean energy supply chain will hold enormous geopolitical leverage over those that do not.', 'geopolitics', 'opinion', true),
('The Arctic Is the Next Great Power Competition', 'As ice melts, new shipping lanes open and untapped resource deposits become accessible. Russia, China, Canada, and the US are quietly positioning for control of the Arctic in ways that could reshape global trade and military strategy within a generation.', 'geopolitics', 'opinion', true),
('Pakistan Is a Failed State That Nuclear Weapons Have Made Untouchable', 'With chronic economic crises, military coups, and insurgencies, Pakistan would be treated as a pariah state were it not for its nuclear arsenal. The international community''s inability to address this paradox represents one of the most dangerous unresolved geopolitical problems.', 'geopolitics', 'opinion', true),
('Europe''s Strategic Dependency on the US Is Its Greatest Vulnerability', 'Decades of underinvestment in defence under the American security umbrella have left Europe militarily incapable of acting independently. Russia''s invasion of Ukraine revealed this starkly — the question is whether Europe will finally build the strategic autonomy it has discussed for 30 years.', 'geopolitics', 'opinion', true),
('The War in Ukraine Has Permanently Redefined European Security', 'February 2022 shattered the post-Cold War security architecture. NATO has expanded, defence budgets are rising, and the neutrality of Finland and Sweden has ended. Whatever the outcome in Ukraine, European security will never look the same again.', 'geopolitics', 'opinion', true),
('Southeast Asia Will Be the Economic Battleground of the 2030s', 'Vietnam, Indonesia, the Philippines, and Thailand sit at the intersection of US-China rivalry and are experiencing the fastest manufacturing relocation in modern history. The region that navigates this best will define the next era of global growth.', 'geopolitics', 'opinion', true),
('Israel-Gaza Has Permanently Damaged US Soft Power in the Global South', 'The gap between Western rhetoric on human rights and the response to Gaza has not gone unnoticed across Africa, Asia, and Latin America. The reputational damage to the rules-based international order may outlast the conflict by decades.', 'geopolitics', 'opinion', true),
('Latin America Is Drifting Toward Authoritarianism Again', 'From Venezuela to Nicaragua to the fragile democracies in Bolivia and Peru, the region is experiencing a slow democratic backslide. The conditions that produced populist strongmen in the 20th century — inequality, weak institutions, and external debt — are reasserting themselves.', 'geopolitics', 'opinion', true),
('The Age of Multilateralism Is Over — Minilateralism Has Replaced It', 'The WTO is paralysed, the UN Security Council is gridlocked, and the IMF is losing legitimacy in the Global South. In their place, smaller coalitions — the Quad, AUKUS, I2U2 — are doing the real work of international cooperation. This is either pragmatic or a sign of systemic collapse.', 'geopolitics', 'opinion', true),
('China''s Belt and Road Initiative Is Failing Quietly', 'After more than a decade and over $1 trillion in loans, many BRI projects have stalled, been cancelled, or become debt traps. Sri Lanka''s Hambantota Port became a symbol. Beijing is now quietly pivoting toward smaller, higher-quality infrastructure deals with fewer strings.', 'geopolitics', 'opinion', true),
('Inflation Targeting Is the Wrong Framework for the 2020s', 'Central banks built for a world of demand-driven inflation are struggling with supply-side shocks, energy transitions, and demographic change. The 2% target was designed for a different era — clinging to it may produce worse economic outcomes than adopting a broader mandate.', 'macro', 'opinion', true),
('The Global Middle Class Is Shrinking for the First Time in Decades', 'Rising costs of housing, education, and healthcare in developed economies, combined with stagnant wages, are hollowing out the middle class. In emerging markets, progress has stalled. The political consequences of this — already visible in populism — are still early.', 'macro', 'opinion', true),
('AI Productivity Gains Will Not Show Up in GDP Statistics', 'Much of the value AI creates — faster decisions, eliminated friction, better outcomes — won''t be captured by traditional GDP measurement. We are entering an era where economic wellbeing diverges significantly from measured output, creating dangerous misreadings of the real economy.', 'macro', 'opinion', true),
('The Next Recession Will Be Caused by Commercial Real Estate', 'Office vacancy rates in major cities are at historic highs, loan maturities are clustering, and regional banks hold concentrated exposure. When these loans start defaulting at scale, the contagion effects on credit markets could trigger a recession more severe than currently anticipated.', 'macro', 'opinion', true),
('Quantitative Tightening Has Never Been Tested at This Scale', 'Central banks are unwinding balance sheets that dwarfed anything seen before. The feedback loops between QT, bond market liquidity, and bank stability are poorly understood. We are running an experiment in real time with the global financial system.', 'macro', 'opinion', true),
('Currency Wars Are Back and More Dangerous Than Before', 'Competitive devaluations, capital controls, and strategic reserve diversification away from the dollar are accelerating. Unlike the 1930s, this round is happening within a much more interconnected financial system, making contagion faster and harder to contain.', 'macro', 'opinion', true),
('Commodity Supercycles Drive More Economic History Than Economists Admit', 'Oil in the 1970s, metals in the 2000s, and now the energy transition minerals of the 2020s — commodity cycles repeatedly determine which nations prosper and which stagnate. Yet mainstream macro models consistently underweight resource dynamics in their forecasts.', 'macro', 'opinion', true),
('The Global Savings Glut Is Over and Asset Prices Have Not Adjusted', 'Decades of surplus savings from Asia and petrostates suppressed interest rates and inflated asset valuations. As demographics shift, current accounts rebalance, and sovereign wealth funds spend rather than save, the structural bid for financial assets is quietly disappearing.', 'macro', 'opinion', true),
('Shadow Banking Is Larger Than the Regulated System and Nobody Is Watching', 'Private credit funds, money market funds, and non-bank lenders now intermediate more credit than regulated banks in many countries. The 2008 crisis showed what happens when shadow banking unravels — we have learned little and the sector is twice as large now.', 'macro', 'opinion', true),
('Stagflation Is the Default State for the 2030s', 'Deglobalisation raises costs. Energy transition is disinflationary long-term but inflationary near-term. Ageing workforces reduce supply. Fiscal deficits remain structural. The combination points persistently toward above-target inflation coexisting with below-trend growth — a macro regime most policymakers are unprepared to manage.', 'macro', 'opinion', true);
