/*
  # Add Topic Bank Batch 3: Finance, Society, Health, Environment, Business, Consulting, Science

  Adds 42 high-quality distinct opinion topics across these domains.
*/

INSERT INTO agent_topics (title, description, domain, post_type, is_active) VALUES
-- FINANCE
('Passive Investing Is Distorting Capital Allocation at Scale', 'Index funds now own such large stakes in public companies that they cannot price individual stocks efficiently or exert meaningful governance pressure. The irony is that passive investing only works as long as enough active investors exist to set prices — it is a free rider problem reaching critical mass.', 'finance', 'opinion', true),
('The Venture Capital Model Is Broken for Deep Tech', 'Ten-year fund cycles and pressure for portfolio markups within three years are structurally incompatible with the timelines needed for nuclear, biotech, and materials science companies. The capital that built the internet is the wrong capital for building the next generation of physical infrastructure.', 'finance', 'opinion', true),
('Retail Investors Have Permanently Changed Market Microstructure', 'The GameStop moment revealed that organised retail trading can overwhelm institutional short positions. Social media-coordinated investing, zero-commission brokers, and meme-stock dynamics have introduced a structural volatility factor into markets that quant models were never designed to handle.', 'finance', 'opinion', true),
('The Insurance Industry Is Quietly Withdrawing from Climate Risk', 'Insurers have pulled out of California, Florida, and Louisiana and are repricing coastal and wildfire risk at rates that make property ownership unaffordable. This quiet withdrawal is a real-time market signal about climate risk that equity markets are ignoring at their peril.', 'finance', 'opinion', true),
('Central Bank Digital Currencies Will Accelerate Financial Surveillance', 'Every major central bank is exploring digital currencies that would give governments complete transaction visibility. The financial privacy that cash provides, imperfect as it is, would be eliminated. This is a surveillance expansion that is proceeding largely without democratic debate.', 'finance', 'opinion', true),
('The Private Equity Secondaries Market Is Hiding a Valuation Crisis', 'PE funds mark their own portfolios, creating valuations that have not been stress-tested by public market pricing. As interest rates stay elevated and exit windows narrow, the gap between reported NAVs and realised values is becoming a systemic risk that regulators are only beginning to examine.', 'finance', 'opinion', true),
('Tokenisation of Real-World Assets Will Be Finance''s Biggest Structural Shift Since ETFs', 'Putting bonds, real estate, private equity, and commodities on-chain reduces settlement times, lowers minimum investment sizes, and creates programmable compliance. The infrastructure for this exists now — what''s missing is regulatory clarity, not technology.', 'finance', 'opinion', true),
('Green Finance Is Mostly Greenwashing at Institutional Scale', 'ESG-labelled funds systematically hold the same companies as standard benchmarks, sustainability bonds fund projects that would have happened anyway, and carbon offset markets are rife with double-counting. The gap between green finance marketing and measurable environmental impact is vast.', 'finance', 'opinion', true),

-- SOCIETY
('Loneliness Is the Defining Public Health Crisis of the 21st Century', 'Rates of social isolation have been rising across the developed world for decades, predating social media. Loneliness produces mortality effects comparable to smoking 15 cigarettes a day. No government has yet treated this as the systemic health emergency the evidence demands.', 'society', 'opinion', true),
('The Degree Premium Is Collapsing and Universities Have Not Noticed', 'The wage premium for a four-year degree has been declining for a decade. For many majors and many institutions, the debt-adjusted return is now negative. A system that has not updated its value proposition since the 1970s is facing a structural reckoning.', 'society', 'opinion', true),
('Trust in Institutions Has Fallen Below the Level Needed for Democratic Governance', 'Trust in government, media, judiciary, and science has declined to levels that make collective action on complex problems almost impossible. COVID, financial crises, and political polarisation have accelerated a trend that started with the failure of the Iraq War.', 'society', 'opinion', true),
('The Gig Economy Has Created a Two-Tier Labour Market With No Floor', 'Platform workers lack benefits, job security, and collective bargaining rights that shaped the economic security of the 20th century middle class. The productivity gains from platform labour are flowing almost entirely to platform owners and consumers, not to the workers creating the value.', 'society', 'opinion', true),
('Urbanisation Is Accelerating Inequality Faster Than Any Other Economic Force', 'The productivity gap between major cities and the rest of the country has widened dramatically in the last 20 years. Housing costs have turned this into a geography of opportunity that systematically benefits those already in advantaged locations. The political backlash to this is still building.', 'society', 'opinion', true),
('Men Are Falling Behind in Education and Nobody Wants to Talk About It', 'Women now outnumber men in higher education in most developed countries by a growing margin. Boys underperform in schools, men have higher suicide rates, and male labour force participation has declined for 50 years. A society that ignores this will face consequences in health, crime, and political radicalisation.', 'society', 'opinion', true),
('Immigration Policy Is the Critical Infrastructure Policy Nobody Treats It As', 'The demographic math of ageing societies requires net immigration to sustain labour supply, pension systems, and public finances. Yet immigration is treated as a cultural debate rather than an economic infrastructure question, leading to policies that are both politically toxic and economically self-defeating.', 'society', 'opinion', true),
('Mental Health Is Now a Corporate Liability, Not Just a Social Issue', 'Workforce depression, anxiety, and burnout cost the global economy over $1 trillion annually in lost productivity. Companies that ignore this are not just failing their employees — they are carrying an unpriced liability that materialises in attrition, medical costs, and performance degradation.', 'society', 'opinion', true),

-- HEALTH
('The Pharmaceutical Patent System Is Killing More People Than It Saves', 'Artificially high prices, extended exclusivity periods, and lack of investment in neglected tropical diseases are all products of a patent regime designed around profit rather than health outcomes. More people die from lack of access to existing medicines than from lack of new ones.', 'health', 'opinion', true),
('Obesity Is a Metabolic Disease, Not a Willpower Failure', 'Decades of treating obesity as a personal failure have been scientifically discredited. The hormonal, genetic, and environmental determinants of weight are now well understood. GLP-1 drugs like Ozempic are the first pharmacological evidence that this reframing is correct and the implications for healthcare systems are vast.', 'health', 'opinion', true),
('The Antibiotic Resistance Crisis Is Being Managed as a Future Problem When It Is Already Here', 'Over 1.2 million people die annually from antibiotic-resistant infections — more than HIV/AIDS. Routine surgeries are becoming life-threatening. The incentive structure for developing new antibiotics is broken. This is not a future scenario; it is a present emergency.', 'health', 'opinion', true),
('Mental Health Apps Are Wellness Theater, Not Healthcare', 'The $5 billion mental health app market offers little evidence of clinical efficacy for serious mental illness. Most products are designed to drive engagement metrics, not improve outcomes. They are filling the space that underfunded mental health services should occupy, while providing a false sense of progress.', 'health', 'opinion', true),
('Preventive Healthcare Is the Greatest Unrealised ROI in Modern Medicine', 'Health systems spend 95% of resources on treatment and 5% on prevention, despite overwhelming evidence that prevention delivers better outcomes at lower cost. The political economy of healthcare — which rewards procedures over outcomes — is the primary reason this obvious reallocation has never happened.', 'health', 'opinion', true),
('Longevity Science Is About to Collide With Insurance, Pensions, and Social Policy', 'Treatments that meaningfully extend healthy human lifespan from 2030 onwards will create a financial and social reckoning: pension systems calibrated for a fixed lifespan will collapse, insurance actuarial tables will be wrong, and societies will need to rethink retirement entirely.', 'health', 'opinion', true),

-- ENVIRONMENT
('Carbon Markets Are Not a Climate Solution, They Are Climate Delay', 'The voluntary carbon offset market is systematically overstating emissions reductions. Companies using offsets to claim net-zero status are, in many cases, not reducing emissions at all — they are purchasing the appearance of action. This institutional greenwashing is slowing genuine decarbonisation.', 'environment', 'opinion', true),
('The Energy Transition Will Create More Geopolitical Conflict Than Fossil Fuels Did', 'Lithium in Chile, cobalt in the Congo, and nickel in Indonesia will produce resource competition as intense as the oil conflicts of the 20th century. The clean energy future is not inherently more peaceful — it just shifts the geography of conflict.', 'environment', 'opinion', true),
('Nuclear Fusion Will Arrive Too Late to Matter for the 2030s Climate Targets', 'Commercial fusion has been 30 years away for 70 years. Even with genuine breakthroughs at NIF and private ventures like Commonwealth Fusion, commercial deployment before 2040 is unlikely. Climate policy must be built around the technologies available today, not the ones we hope for.', 'environment', 'opinion', true),
('Plastic Pollution Will Outlast Civilisation', 'Microplastics have been found in human blood, breast milk, and placentas. They are in the deep ocean and at the summit of Everest. The feedback loops between plastic pollution, endocrine disruption, and ecosystem collapse are poorly understood and may be irreversible.', 'environment', 'opinion', true),
('Geoengineering Will Be Deployed Unilaterally Before Any International Governance Exists', 'Solar radiation management — dispersing aerosols to reflect sunlight — is technically feasible, cheap enough for a single nation to attempt, and carries risks that would affect the entire planet. The governance gap between what is technically possible and what is internationally managed is dangerous.', 'environment', 'opinion', true),
('Biodiversity Loss Is a Bigger Economic Risk Than Climate Change', 'Natural systems provide services worth more than global GDP — pollination, water filtration, carbon sequestration, disease regulation. The collapse of insect populations, coral reefs, and rainforests is dismantling this infrastructure faster than climate models project. Financial markets are not pricing this risk at all.', 'environment', 'opinion', true),

-- BUSINESS
('The D2C Revolution Is Retreating Back to Retail', 'Brands that bypassed retailers to sell direct-to-consumer discovered that customer acquisition costs, logistics complexity, and the absence of retail discovery made the model far less profitable than projected. The retreat to wholesale and marketplace channels is rewriting the DTC playbook.', 'business', 'opinion', true),
('Creator Economy Valuations Are Disconnected From Creator Economics', 'Platforms valued at billions based on creator activity conceal the fact that the median creator earns below minimum wage. The platform captures the network effects; the creator captures the brand risk and labour. This imbalance will produce a creator unionisation movement within this decade.', 'business', 'opinion', true),
('Food Delivery Economics Are Fundamentally Broken', 'Despite over a decade of scale and billions in subsidy, Uber Eats, DoorDash, and Deliveroo have not produced consistently profitable businesses. The unit economics of on-demand food delivery — drivers, insurance, support, and packaging — may simply not allow for sustainable margins in most markets.', 'business', 'opinion', true),
('The Sharing Economy Delivered Convenience but Destroyed Belonging', 'Airbnb hollowed out neighbourhoods, Uber displaced community-owned transport, and WeWork sold nomadism as a virtue. The sharing economy delivered efficiency gains at the cost of the social infrastructure — local ownership, community ties, stable employment — that makes cities liveable.', 'business', 'opinion', true),
('B2B Software Valuations Have Reset Permanently', 'The SaaS multiples of 2020-2021 — 30x, 50x, 100x revenue — were a product of zero interest rates and growth-at-any-cost capital allocation. The reset to 5-10x for most businesses is not a temporary correction; it reflects what cash flow-generating software businesses are actually worth.', 'business', 'opinion', true),
('Airport Retail Is the Last Great Captive Audience Business', 'Duty-free, food and beverage, and luxury retail at airports operate in one of the last remaining environments where consumers are time-rich, spend-inclined, and unable to comparison-shop. The economics of this model have survived e-commerce, smartphones, and price transparency in a way almost no other retail category has.', 'business', 'opinion', true),

-- CONSULTING
('Strategy Consulting Is Selling Confidence, Not Answers', 'The primary product of a McKinsey or BCG engagement is not a 200-page deck — it is the organisational permission to make a decision that leadership already suspects is right. Consultants are legitimacy laundering services, and there is nothing wrong with that, but clients should understand what they are buying.', 'consulting', 'opinion', true),
('The MBB Model Is Incompatible With the Speed of Modern Business', 'Six-month projects, 30-person teams, and $20 million fees were designed for an era of slower strategic cycles. Today''s businesses need decisions in weeks, not quarters. The consulting model is evolving faster than the major firms are admitting — and boutiques and AI tools are the primary beneficiaries.', 'consulting', 'opinion', true),
('Consulting Firms Have a Conflict of Interest Problem They Are Not Resolving', 'The same firms that audit a company''s strategy often sell the transformation to fix it, and then staff the implementation. Every step creates a financial incentive to find more work. The industry''s self-policing of these conflicts is demonstrably inadequate given the volume of reported failures.', 'consulting', 'opinion', true),
('The Rise of Fractional Executives Is Disrupting the Consulting Model', 'Seasoned operators available on fractional terms — three days a week, project-based, embedded in the business — are outcompeting traditional consultants because they take accountability for outcomes, not just advice. This structural shift in the market for senior expertise is still underreported.', 'consulting', 'opinion', true),

-- SCIENCE
('mRNA Technology Will Reshape Medicine Beyond COVID Vaccines', 'The success of Pfizer-BioNTech and Moderna proved that mRNA can be manufactured at scale and deployed rapidly. Oncology vaccines personalised to individual tumour profiles, HIV vaccines, and treatments for rare genetic diseases are now in trials. This platform technology is the most consequential pharmaceutical advance in a generation.', 'science', 'opinion', true),
('We Are Dramatically Underinvesting in Pandemic Preparedness Given COVID''s Lessons', 'COVID cost the global economy over $12 trillion. The total annual budget of the WHO is less than $3 billion. We knew a pandemic of this scale was coming — dozens of public health experts had warned of exactly this scenario. The political will to fund preparedness has already faded.', 'science', 'opinion', true),
('Neuroscience Is About to Make Free Will Legally and Ethically Problematic', 'Brain scanning technology can now predict decisions before subjects are consciously aware of them. Neural correlates of violent behaviour, addiction, and psychiatric conditions are increasingly identifiable. The legal and ethical frameworks built on concepts of individual responsibility are entirely unprepared for these findings.', 'science', 'opinion', true),
('Human Genetic Enhancement Will Arrive Before Societies Are Ready for It', 'CRISPR and its successors make germline genetic editing technically feasible. China has already crossed this line. Once early movers demonstrate health and cognitive advantages in edited children, the pressure on other societies to follow will be irresistible. The bioethics conversation is a decade behind the technology.', 'science', 'opinion', true);
