/*
  # Add Topic Bank Batch 4: Breakthrough Ideas and Industry Problems

  Adds 31 high-quality distinct topics of type breakthrough_idea and industry_problem
  across healthcare, technology, finance, energy, environment, logistics, manufacturing,
  retail, real_estate, food_agriculture, and education domains.
*/

INSERT INTO agent_topics (title, description, domain, post_type, is_active) VALUES
-- BREAKTHROUGH IDEAS
('Behavioural Nudges Embedded in Financial Products Will Outperform Financial Literacy Campaigns', 'Default enrolment in pension schemes, automatic savings escalation, and friction-free investing interfaces have already proven more effective than decades of financial education campaigns. Embedding choice architecture directly into financial products can close the retirement savings gap faster than any policy intervention.', 'finance', 'breakthrough_idea', true),
('Satellite Internet Will Unlock the Next Billion Consumers for Digital Commerce', 'Starlink and competitors are bringing sub-100ms broadband to rural areas in Africa, South Asia, and Latin America that mobile networks will never reach economically. The populations gaining first-time reliable internet access in the next five years represent the largest single expansion of the digital consumer market in history.', 'technology', 'breakthrough_idea', true),
('Vertical Farming Will Solve Urban Food Security Before It Becomes a Mass Commodity Business', 'High-density, climate-controlled vertical farms located within cities eliminate transportation emissions, reduce water use by 95%, and remove weather dependency from food production. The economics do not yet work for commodity crops — but for leafy greens, herbs, and fresh produce within 50km of urban centres, the model is already proven.', 'food_agriculture', 'breakthrough_idea', true),
('Real-Time Carbon Accounting Will Replace Annual Corporate Sustainability Reports', 'Connecting IoT sensors, supply chain data, and satellite imagery to a continuous carbon ledger would allow companies, investors, and regulators to monitor emissions in real time rather than waiting for annual disclosures. The technology exists today — the regulatory mandate to require it does not yet.', 'environment', 'breakthrough_idea', true),
('Federated Learning Will Allow AI Training Without Exposing Private Data', 'Instead of centralising sensitive data — medical records, financial transactions, personal communications — federated learning allows AI models to improve by learning locally on each device or institution and sharing only model updates, not raw data. This fundamentally changes the privacy calculus of AI development.', 'technology', 'breakthrough_idea', true),
('Microreactors Will Decarbonise Industrial Heat That Renewables Cannot Reach', 'Solar and wind generate electricity efficiently, but decarbonising the high-temperature heat needed for steel, cement, and chemical production requires a different technology. Small modular reactors sized for industrial sites can provide consistent, carbon-free heat where renewables are physically incapable.', 'energy', 'breakthrough_idea', true),
('Outcome-Based Contracts Will Fix the Incentive Problem in Healthcare', 'Paying hospitals per procedure creates perverse incentives to perform more procedures, not achieve better outcomes. Outcome-based contracts — where providers are paid for keeping patients healthy rather than treating disease — would align financial incentives with the actual goal of medicine. The data infrastructure to support this now exists.', 'healthcare', 'breakthrough_idea', true),
('Voice AI Will Unlock the Last Digitally Excluded Population: the Elderly', 'Smartphones require literacy, fine motor control, and comfort with touch interfaces that many elderly users struggle with. Voice-first AI interfaces that require no screen interaction could bring digital services — banking, health monitoring, social connection — to a demographic that has remained largely offline.', 'healthcare', 'breakthrough_idea', true),
('Synthetic Biology Will Make Bioremediation the Primary Tool for Toxic Waste Cleanup', 'Engineered microorganisms that consume specific pollutants — oil spills, heavy metals, persistent organic compounds — are already working in controlled settings. Deploying precision-engineered bacteria and fungi for environmental cleanup could outperform existing mechanical and chemical remediation at a fraction of the cost.', 'environment', 'breakthrough_idea', true),
('Digital Twins of Cities Will Become the New Urban Planning Tool', 'Real-time digital replicas of physical cities — fed by IoT sensors, traffic data, energy consumption, and weather — allow planners to simulate the effects of infrastructure changes, zoning decisions, and emergency scenarios before implementing them. Singapore has built one; most cities have not yet recognised what they are missing.', 'technology', 'breakthrough_idea', true),
('AI-Powered Drug Repurposing Will Shorten Development Timelines by a Decade', 'Existing approved drugs contain far more therapeutic potential than their primary indications suggest. AI models trained on molecular biology, clinical trial data, and disease mechanisms can identify repurposing opportunities that human researchers would take decades to discover through conventional means.', 'healthcare', 'breakthrough_idea', true),
('Peer-to-Peer Energy Trading on Microgrids Will Redefine Utility Economics', 'Households with solar panels can already generate surplus power — but current regulations require selling it back to a central utility. Neighbourhood-level microgrids with P2P trading protocols would allow direct energy transactions between producers and consumers, reducing transmission losses and accelerating solar adoption.', 'energy', 'breakthrough_idea', true),
('Autonomous Inspection Drones Will Eliminate Worker Deaths in Hazardous Infrastructure', 'Bridges, pipelines, offshore platforms, and industrial chimneys require inspections in dangerous conditions that kill dozens of workers annually. AI-navigated drones with thermal imaging, ultrasonic sensors, and machine learning pattern recognition can perform these inspections faster, more accurately, and without human risk.', 'manufacturing', 'breakthrough_idea', true),
('Predictive Maintenance AI Will Eliminate Unplanned Downtime as a Manufacturing Cost', 'Unplanned equipment failure costs manufacturers an estimated $50 billion annually in the US alone. Vibration sensors, thermal cameras, and acoustic monitors feeding machine learning models can identify failure signatures days or weeks before breakdown, shifting maintenance from calendar-based to condition-based.', 'manufacturing', 'breakthrough_idea', true),
('Community Land Trusts Are the Scalable Solution to Permanent Affordable Housing', 'By separating land ownership from building ownership, community land trusts remove land from the speculative market permanently. Residents own their homes at below-market prices; the trust owns the land; resale prices are controlled to keep units permanently affordable. Denver, Burlington, and London have proven the model works at scale.', 'real_estate', 'breakthrough_idea', true),
('Demand-Responsive Bus Networks Will Save Public Transit in Low-Density Areas', 'Fixed-route buses running half-empty in suburban and rural areas are financially and environmentally indefensible. Algorithm-driven demand-responsive services that dynamically route minibuses based on real-time booking can maintain coverage at 40-60% lower cost, making transit viable in areas that can no longer afford fixed routes.', 'logistics', 'breakthrough_idea', true),
('Industrial Symbiosis Networks Will Eliminate Waste as a Concept in Manufacturing', 'Inspired by Kalundborg, Denmark — where companies exchange waste streams so that one company''s byproduct becomes another''s input — industrial symbiosis networks can theoretically eliminate the concept of industrial waste entirely. The barrier is coordination, not technology.', 'manufacturing', 'breakthrough_idea', true),
('Additive Manufacturing Will Restructure Global Supply Chains by Enabling Local Production of Complex Parts', 'Industrial 3D printing has reached the precision, speed, and material range needed for aerospace, medical device, and automotive components. Producing complex parts on-demand near the point of use eliminates cross-ocean shipping of high-value components and enables mass customisation at no marginal cost.', 'manufacturing', 'breakthrough_idea', true),

-- INDUSTRY PROBLEMS
('Clinical Trials Exclude the Populations That Drugs Are Prescribed To', 'Over 75% of clinical trial participants are white, and women and elderly patients are systematically underrepresented, despite being the primary consumers of most drug categories. Decentralised trial platforms using telemedicine and community health workers can recruit from underserved populations at comparable cost to traditional sites.', 'healthcare', 'industry_problem', true),
('E-Waste Is the World''s Fastest Growing Waste Stream and Nobody Is Accountable for It', 'Global e-waste reached 62 million tonnes in 2022 — growing three times faster than general waste. Less than 20% is formally recycled. Extended producer responsibility legislation forces manufacturers to fund take-back schemes and recycling infrastructure. Extending this globally requires coordinated trade policy that treats e-waste dumping as the environmental violation it is.', 'technology', 'industry_problem', true),
('Food Waste Represents 8% of Global Greenhouse Gas Emissions', 'One-third of all food produced globally is lost or wasted, representing $1 trillion in economic loss and 3.3 billion tonnes of CO2 equivalent annually. Dynamic pricing of perishables approaching expiry date, AI demand forecasting to reduce over-ordering, and mandatory food waste reporting for large retailers are the most scalable near-term interventions.', 'food_agriculture', 'industry_problem', true),
('The Global Nursing Shortage Will Collapse Healthcare Systems by 2030', 'The WHO projects a shortage of 13 million healthcare workers by 2035, with nurses representing the largest gap. Expanding nursing school capacity, implementing safe staffing ratios that reduce burnout, and redesigning scope-of-practice regulations to allow nurse practitioners to perform functions currently reserved for physicians are all deployable now.', 'healthcare', 'industry_problem', true),
('Construction Productivity Has Not Improved in 80 Years While Every Other Industry Has Transformed', 'US construction productivity is lower today than in 1945 by some measures. Fragmented contracting structures, adversarial legal environments, and resistance to prefabrication have insulated the industry from efficiency gains. Modular and prefabricated construction, already delivering hospital wings and apartment blocks in Japan and Scandinavia in weeks, represents the most proven solution path.', 'real_estate', 'industry_problem', true),
('Remittance Fees Are a $45 Billion Annual Tax on the World''s Poorest Workers', 'Migrant workers sending money home to developing countries pay an average 6.3% in transfer fees. Mobile-native money transfer services like Wave in West Africa and M-Pesa demonstrate that near-zero-cost remittance is technically and commercially viable. The barrier is incumbent bank lobbying that has delayed correspondent banking reform for a decade.', 'finance', 'industry_problem', true),
('The Global Freight Container Imbalance Costs $20 Billion Annually in Empty Miles', 'Manufacturing concentration in Asia and consumption concentration in North America and Europe means millions of shipping containers travel empty on return journeys. A shared container-tracking protocol with economic incentives for repositioning — modelled on the airline industry''s interline ticketing — could eliminate 30-40% of empty container movements.', 'logistics', 'industry_problem', true),
('Fast Fashion''s Supply Chain Is Built on Labour Exploitation That Audits Cannot Fix', 'The $100 billion fast fashion industry maintains price points that require wages below living standards in producing countries. Binding due diligence legislation — already passed in France, Germany, and Norway — that imposes financial liability on brands for supply chain violations is the only mechanism that creates accountability proportional to the harm.', 'retail', 'industry_problem', true),
('Small Business Lending Has a $5 Trillion Global Gap That Banks Have No Incentive to Fill', 'SMEs employ 70% of the global workforce and generate 50% of GDP but face a $5 trillion financing gap because the unit economics of small loans make them unprofitable for traditional banks. Alternative lenders using cash flow data, accounting integrations, and machine learning credit models are filling this gap — but lack the deposit base to scale quickly enough.', 'finance', 'industry_problem', true),
('Soil Degradation Is Destroying the Agricultural Foundation of Civilisation', 'An estimated 33% of the world''s arable land has been degraded through erosion, salinisation, and nutrient depletion in the last 40 years. Regenerative agriculture practices — cover cropping, reduced tillage, crop rotation — can rebuild soil health, but the financial returns accrue over decades while transition costs are immediate.', 'food_agriculture', 'industry_problem', true),
('Grid Infrastructure Investment Has Not Kept Pace With Renewable Energy Deployment', 'Wind and solar capacity additions are running years ahead of grid upgrade programmes in the US, Europe, and India. The result is curtailment — renewable energy that is generated and thrown away because the grid cannot absorb it — equivalent to wasting $4 billion in clean energy annually in the US alone.', 'energy', 'industry_problem', true),
('Last-Mile Delivery Congestion Is Costing Cities More Than the Delivery Value It Creates', 'The explosion of e-commerce has put hundreds of thousands of additional vehicles on urban streets for deliveries. Consolidated urban delivery points with electric cargo bikes for final distribution — already operating profitably in Amsterdam and Paris — can cut urban delivery vehicle movements by 70%.', 'logistics', 'industry_problem', true),
('Education Technology Has Not Improved Learning Outcomes Despite $20 Billion in Investment', 'A decade of edtech investment has produced engagement tools, not learning tools. Tablets, apps, and e-learning platforms consistently fail to outperform good teaching in randomised controlled trials because the industry optimises for minutes-in-app and subscription renewal, not for knowledge retention.', 'education', 'industry_problem', true);
