export const COUNTRY_NAMES: Record<string, string[]> = {
  "Nigeria": ["Emeka", "Chisom", "Adebayo", "Funmi", "Tunde", "Ngozi", "Seun", "Amara", "Biodun", "Kemi"],
  "Ghana": ["Kwame", "Abena", "Kofi", "Akosua", "Yaw", "Ama", "Kweku", "Adwoa", "Nana", "Efua"],
  "Kenya": ["Wanjiru", "Kamau", "Akinyi", "Otieno", "Wanjiku", "Mutua", "Zawadi", "Odhiambo", "Njeri", "Kipchoge"],
  "South Africa": ["Thabo", "Zanele", "Sipho", "Nomvula", "Bongani", "Lindiwe", "Lungelo", "Nompumelelo", "Siyanda", "Ayanda"],
  "Ethiopia": ["Biruk", "Tigist", "Yonas", "Selam", "Dawit", "Hana", "Abel", "Meron", "Kidus", "Liya"],
  "Tanzania": ["Juma", "Amina", "Baraka", "Fatuma", "Said", "Zawadi", "Hamisi", "Neema", "Rashidi", "Rehema"],
  "Uganda": ["Kampala", "Naledi", "Ssekandi", "Namukasa", "Mutebi", "Nakato", "Wasswa", "Nambooze", "Kiprotich", "Akello"],
  "Egypt": ["Ahmed", "Fatima", "Mohamed", "Nour", "Omar", "Sara", "Kareem", "Dina", "Youssef", "Rana"],
  "Morocco": ["Youssef", "Fatima", "Hassan", "Nadia", "Karim", "Samira", "Mehdi", "Zineb", "Amine", "Hajar"],
  "India": ["Arjun", "Priya", "Rahul", "Sneha", "Vikram", "Kavya", "Rohan", "Meera", "Aditya", "Ananya"],
  "Pakistan": ["Hassan", "Ayesha", "Usman", "Zainab", "Bilal", "Fatima", "Imran", "Sana", "Hamza", "Nadia"],
  "Bangladesh": ["Rahim", "Nusrat", "Kamal", "Fatema", "Shakib", "Tania", "Hasan", "Mitu", "Rafi", "Riya"],
  "Sri Lanka": ["Nuwan", "Dilini", "Chamara", "Sachini", "Asanka", "Thilini", "Kasun", "Nadeesha", "Pradeep", "Isuri"],
  "China": ["Wei", "Fang", "Ming", "Ling", "Jian", "Xiu", "Hao", "Yan", "Bin", "Mei"],
  "Japan": ["Kenji", "Yuki", "Hiroshi", "Sakura", "Takeshi", "Aoi", "Ryota", "Hana", "Shota", "Nana"],
  "South Korea": ["Jinho", "Jiyeon", "Minjun", "Soyeon", "Seungho", "Yuna", "Hyunwoo", "Jisoo", "Taehyun", "Minji"],
  "Indonesia": ["Budi", "Sari", "Agus", "Dewi", "Eko", "Rina", "Hendra", "Fitri", "Bambang", "Wulan"],
  "Philippines": ["Carlo", "Maria", "Juan", "Ana", "Jose", "Rosa", "Ramon", "Luisa", "Manuel", "Carla"],
  "Vietnam": ["Minh", "Lan", "Hung", "Linh", "Nam", "Thu", "Duc", "Mai", "Tuan", "Hoa"],
  "Thailand": ["Somchai", "Nong", "Chai", "Ning", "Pong", "Pim", "Nit", "Kwan", "Arm", "Aom"],
  "Malaysia": ["Ahmad", "Siti", "Razif", "Nurul", "Hafiz", "Aishah", "Izzat", "Farah", "Azlan", "Nadia"],
  "Brazil": ["Lucas", "Mariana", "Pedro", "Fernanda", "Rafael", "Camila", "Thiago", "Beatriz", "Gustavo", "Juliana"],
  "Mexico": ["Carlos", "Sofia", "Miguel", "Valentina", "Diego", "Isabella", "Alejandro", "Gabriela", "Eduardo", "Daniela"],
  "Colombia": ["Santiago", "Valeria", "Andres", "Natalia", "Julian", "Camila", "Sebastian", "Laura", "Felipe", "Maria"],
  "Argentina": ["Mateo", "Lucia", "Franco", "Martina", "Ezequiel", "Valentina", "Agustin", "Florencia", "Nicolas", "Paula"],
  "Peru": ["Diego", "Gabriela", "Javier", "Lorena", "Aldo", "Carla", "Ivan", "Rosa", "Miguel", "Patricia"],
  "Chile": ["Rodrigo", "Constanza", "Cristian", "Daniela", "Francisco", "Javiera", "Nicolas", "Valeria", "Andres", "Macarena"],
  "Venezuela": ["Andres", "Maria", "Juan", "Sofia", "Carlos", "Ana", "Miguel", "Isabel", "Luis", "Carolina"],
  "United States": ["Jamie", "Sam", "Alex", "Morgan", "Riley", "Jordan", "Casey", "Taylor", "Avery", "Drew"],
  "Canada": ["Jamie", "Sam", "Alex", "Morgan", "Riley", "Jordan", "Casey", "Taylor", "Avery", "Drew"],
  "United Kingdom": ["Jamie", "Sam", "Alex", "Morgan", "Riley", "Jordan", "Casey", "Taylor", "Avery", "Drew"],
  "Australia": ["Liam", "Olivia", "Jack", "Charlotte", "Noah", "Ava", "James", "Mia", "William", "Amelia"],
  "New Zealand": ["Liam", "Olivia", "Jack", "Charlotte", "Noah", "Isabella", "Lucas", "Sophie", "Ethan", "Emma"],
  "Germany": ["Lukas", "Mia", "Felix", "Hannah", "Leon", "Sophie", "Jonas", "Anna", "Tim", "Laura"],
  "France": ["Louis", "Emma", "Gabriel", "Jade", "Raphaël", "Louise", "Arthur", "Alice", "Lucas", "Chloé"],
  "Spain": ["Alejandro", "Sofia", "Pablo", "Maria", "Daniel", "Lucia", "Carlos", "Julia", "Adrian", "Elena"],
  "Italy": ["Marco", "Sofia", "Luca", "Giulia", "Matteo", "Aurora", "Lorenzo", "Giorgia", "Andrea", "Valentina"],
  "Portugal": ["Joao", "Maria", "Tiago", "Ana", "Miguel", "Inês", "Pedro", "Beatriz", "Ricardo", "Catarina"],
  "Netherlands": ["Daan", "Emma", "Sem", "Mila", "Finn", "Sophie", "Liam", "Julia", "Noah", "Sara"],
  "Sweden": ["Erik", "Emma", "Lars", "Anna", "Karl", "Sara", "Johan", "Maja", "Anders", "Lina"],
  "Norway": ["Lars", "Emma", "Erik", "Nora", "Magnus", "Sofia", "Ola", "Ingrid", "Anders", "Astrid"],
  "Denmark": ["Mikkel", "Emma", "Lars", "Sofie", "Christian", "Sara", "Martin", "Louise", "Peter", "Maja"],
  "Finland": ["Mikko", "Sofia", "Juhani", "Emma", "Olavi", "Aino", "Matti", "Helvi", "Paavo", "Siiri"],
  "Poland": ["Piotr", "Anna", "Krzysztof", "Marta", "Andrzej", "Katarzyna", "Tomasz", "Agnieszka", "Marek", "Barbara"],
  "Russia": ["Alexei", "Natasha", "Dmitri", "Olga", "Ivan", "Anastasia", "Sergei", "Elena", "Viktor", "Maria"],
  "Ukraine": ["Oleksiy", "Olena", "Mykola", "Natalia", "Andriy", "Iryna", "Vasyl", "Oksana", "Dmytro", "Yulia"],
  "Turkey": ["Mehmet", "Ayşe", "Ali", "Fatma", "Ahmet", "Zeynep", "Mustafa", "Elif", "Ibrahim", "Hatice"],
  "Saudi Arabia": ["Mohammed", "Fatima", "Abdullah", "Nora", "Khalid", "Sara", "Ahmed", "Maha", "Omar", "Reem"],
  "UAE": ["Mohammed", "Fatima", "Ahmed", "Maryam", "Khalid", "Aisha", "Omar", "Hessa", "Saif", "Shamsa"],
  "Israel": ["David", "Sarah", "Yosef", "Rachel", "Moshe", "Miriam", "Daniel", "Leah", "Noam", "Tamar"],
  "Iran": ["Ali", "Fateme", "Mohammad", "Zahra", "Hossein", "Maryam", "Reza", "Narges", "Hassan", "Somayeh"],
  "Iraq": ["Mohammed", "Fatima", "Ahmed", "Zainab", "Ali", "Noor", "Hassan", "Mariam", "Omar", "Dina"],
};

export const DEFAULT_NAMES = ["Jamie", "Sam", "Alex", "Morgan", "Riley", "Jordan", "Casey", "Taylor", "Avery", "Drew"];

export function getNamesForCountry(country: string | null | undefined): string[] {
  if (!country) return DEFAULT_NAMES;
  const exact = COUNTRY_NAMES[country];
  if (exact) return exact;
  const lower = country.toLowerCase();
  for (const [key, names] of Object.entries(COUNTRY_NAMES)) {
    if (key.toLowerCase() === lower) return names;
  }
  return DEFAULT_NAMES;
}

export const AGENT_ROLES = [
  { role: "The Skeptic", responseType: "challenge", index: 0 },
  { role: "Risk Analyst", responseType: "risk", index: 1 },
  { role: "The Optimist", responseType: "alternative", index: 2 },
  { role: "Data Detective", responseType: "question", index: 3 },
  { role: "Devil's Advocate", responseType: "alternative", index: 4 },
  { role: "The Historian", responseType: "analysis", index: 5 },
  { role: "Market Analyst", responseType: "analysis", index: 6 },
  { role: "Tech Futurist", responseType: "analysis", index: 7 },
  { role: "Systems Thinker", responseType: "analysis", index: 8 },
  { role: "The Pragmatist", responseType: "analysis", index: 9 },
];

export type TopicDomain = 'finance' | 'technology' | 'politics' | 'health' | 'environment' | 'society' | 'business' | 'science' | 'geopolitics' | 'strategy' | 'consulting' | 'macro' | 'entrepreneurship' | 'economy' | 'healthcare' | 'energy' | 'education' | 'food_agriculture' | 'logistics' | 'manufacturing' | 'real_estate' | 'retail' | 'ai_product' | 'product_development' | 'startup_ops' | 'general';

export const TOPIC_AGENT_WEIGHTS: Record<TopicDomain, Record<string, number>> = {
  finance: {
    "Market Analyst": 10,
    "Risk Analyst": 9,
    "Data Detective": 8,
    "The Historian": 7,
    "The Skeptic": 6,
    "The Pragmatist": 5,
    "Devil's Advocate": 4,
    "Systems Thinker": 3,
    "The Optimist": 2,
    "Tech Futurist": 1,
  },
  technology: {
    "Tech Futurist": 10,
    "Data Detective": 9,
    "Systems Thinker": 8,
    "The Skeptic": 7,
    "The Pragmatist": 6,
    "Devil's Advocate": 5,
    "Risk Analyst": 4,
    "The Optimist": 3,
    "Market Analyst": 2,
    "The Historian": 1,
  },
  politics: {
    "The Historian": 10,
    "Systems Thinker": 9,
    "Devil's Advocate": 8,
    "The Skeptic": 7,
    "Risk Analyst": 6,
    "Data Detective": 5,
    "The Optimist": 4,
    "The Pragmatist": 3,
    "Market Analyst": 2,
    "Tech Futurist": 1,
  },
  health: {
    "Risk Analyst": 10,
    "Data Detective": 9,
    "The Skeptic": 8,
    "Systems Thinker": 7,
    "The Historian": 6,
    "The Pragmatist": 5,
    "The Optimist": 4,
    "Devil's Advocate": 3,
    "Market Analyst": 2,
    "Tech Futurist": 1,
  },
  environment: {
    "Systems Thinker": 10,
    "Risk Analyst": 9,
    "The Historian": 8,
    "Data Detective": 7,
    "The Skeptic": 6,
    "Devil's Advocate": 5,
    "Tech Futurist": 4,
    "The Optimist": 3,
    "The Pragmatist": 2,
    "Market Analyst": 1,
  },
  society: {
    "The Historian": 10,
    "Systems Thinker": 9,
    "The Skeptic": 8,
    "Devil's Advocate": 7,
    "The Optimist": 6,
    "Data Detective": 5,
    "Risk Analyst": 4,
    "The Pragmatist": 3,
    "Market Analyst": 2,
    "Tech Futurist": 1,
  },
  business: {
    "The Pragmatist": 10,
    "Market Analyst": 9,
    "Risk Analyst": 8,
    "Data Detective": 7,
    "The Skeptic": 6,
    "Systems Thinker": 5,
    "Devil's Advocate": 4,
    "The Optimist": 3,
    "The Historian": 2,
    "Tech Futurist": 1,
  },
  science: {
    "Data Detective": 10,
    "The Skeptic": 9,
    "Systems Thinker": 8,
    "Tech Futurist": 7,
    "The Historian": 6,
    "Risk Analyst": 5,
    "Devil's Advocate": 4,
    "The Optimist": 3,
    "The Pragmatist": 2,
    "Market Analyst": 1,
  },
  geopolitics: {
    "The Historian": 10,
    "Systems Thinker": 9,
    "Risk Analyst": 8,
    "Devil's Advocate": 7,
    "The Skeptic": 6,
    "Data Detective": 5,
    "Market Analyst": 4,
    "The Pragmatist": 3,
    "The Optimist": 2,
    "Tech Futurist": 1,
  },
  strategy: {
    "The Pragmatist": 10,
    "Devil's Advocate": 9,
    "Market Analyst": 8,
    "The Skeptic": 7,
    "Systems Thinker": 6,
    "Data Detective": 5,
    "Risk Analyst": 4,
    "The Historian": 3,
    "The Optimist": 2,
    "Tech Futurist": 1,
  },
  consulting: {
    "The Pragmatist": 10,
    "The Skeptic": 9,
    "Devil's Advocate": 8,
    "Market Analyst": 7,
    "Data Detective": 6,
    "Systems Thinker": 5,
    "Risk Analyst": 4,
    "The Optimist": 3,
    "The Historian": 2,
    "Tech Futurist": 1,
  },
  macro: {
    "Market Analyst": 10,
    "Risk Analyst": 9,
    "The Historian": 8,
    "Data Detective": 7,
    "The Skeptic": 6,
    "Systems Thinker": 5,
    "Devil's Advocate": 4,
    "The Pragmatist": 3,
    "The Optimist": 2,
    "Tech Futurist": 1,
  },
  entrepreneurship: {
    "The Pragmatist": 10,
    "Devil's Advocate": 9,
    "The Skeptic": 8,
    "Market Analyst": 7,
    "Tech Futurist": 6,
    "Data Detective": 5,
    "Risk Analyst": 4,
    "The Optimist": 3,
    "Systems Thinker": 2,
    "The Historian": 1,
  },
  economy: {
    "Market Analyst": 10,
    "The Historian": 9,
    "Data Detective": 8,
    "Systems Thinker": 7,
    "Risk Analyst": 6,
    "The Skeptic": 5,
    "Devil's Advocate": 4,
    "The Pragmatist": 3,
    "The Optimist": 2,
    "Tech Futurist": 1,
  },
  healthcare: {
    "Risk Analyst": 10,
    "Data Detective": 9,
    "The Skeptic": 8,
    "Systems Thinker": 7,
    "The Historian": 6,
    "The Pragmatist": 5,
    "The Optimist": 4,
    "Devil's Advocate": 3,
    "Market Analyst": 2,
    "Tech Futurist": 1,
  },
  energy: {
    "Systems Thinker": 10,
    "Tech Futurist": 9,
    "Risk Analyst": 8,
    "The Skeptic": 7,
    "Market Analyst": 6,
    "Data Detective": 5,
    "The Historian": 4,
    "Devil's Advocate": 3,
    "The Pragmatist": 2,
    "The Optimist": 1,
  },
  education: {
    "The Historian": 10,
    "Systems Thinker": 9,
    "The Pragmatist": 8,
    "Data Detective": 7,
    "The Skeptic": 6,
    "Devil's Advocate": 5,
    "The Optimist": 4,
    "Risk Analyst": 3,
    "Market Analyst": 2,
    "Tech Futurist": 1,
  },
  food_agriculture: {
    "Systems Thinker": 10,
    "Risk Analyst": 9,
    "Data Detective": 8,
    "The Pragmatist": 7,
    "Tech Futurist": 6,
    "The Skeptic": 5,
    "The Historian": 4,
    "Devil's Advocate": 3,
    "Market Analyst": 2,
    "The Optimist": 1,
  },
  logistics: {
    "The Pragmatist": 10,
    "Systems Thinker": 9,
    "Tech Futurist": 8,
    "Market Analyst": 7,
    "Data Detective": 6,
    "Risk Analyst": 5,
    "The Skeptic": 4,
    "Devil's Advocate": 3,
    "The Historian": 2,
    "The Optimist": 1,
  },
  manufacturing: {
    "The Pragmatist": 10,
    "Systems Thinker": 9,
    "Risk Analyst": 8,
    "Tech Futurist": 7,
    "Data Detective": 6,
    "Market Analyst": 5,
    "The Skeptic": 4,
    "The Historian": 3,
    "Devil's Advocate": 2,
    "The Optimist": 1,
  },
  real_estate: {
    "Market Analyst": 10,
    "The Pragmatist": 9,
    "Risk Analyst": 8,
    "The Historian": 7,
    "Data Detective": 6,
    "Systems Thinker": 5,
    "The Skeptic": 4,
    "Devil's Advocate": 3,
    "The Optimist": 2,
    "Tech Futurist": 1,
  },
  retail: {
    "Market Analyst": 10,
    "The Pragmatist": 9,
    "Data Detective": 8,
    "The Skeptic": 7,
    "Tech Futurist": 6,
    "Devil's Advocate": 5,
    "Risk Analyst": 4,
    "Systems Thinker": 3,
    "The Optimist": 2,
    "The Historian": 1,
  },
  ai_product: {
    "Tech Futurist": 10,
    "The Pragmatist": 9,
    "The Skeptic": 8,
    "Systems Thinker": 7,
    "Market Analyst": 6,
    "Data Detective": 5,
    "Devil's Advocate": 4,
    "Risk Analyst": 3,
    "The Optimist": 2,
    "The Historian": 1,
  },
  product_development: {
    "The Pragmatist": 10,
    "Market Analyst": 9,
    "The Skeptic": 8,
    "Data Detective": 7,
    "Systems Thinker": 6,
    "Tech Futurist": 5,
    "Devil's Advocate": 4,
    "The Optimist": 3,
    "Risk Analyst": 2,
    "The Historian": 1,
  },
  startup_ops: {
    "The Pragmatist": 10,
    "Risk Analyst": 9,
    "Devil's Advocate": 8,
    "The Skeptic": 7,
    "Market Analyst": 6,
    "Data Detective": 5,
    "The Optimist": 4,
    "Systems Thinker": 3,
    "Tech Futurist": 2,
    "The Historian": 1,
  },
  general: {
    "The Skeptic": 5,
    "Risk Analyst": 5,
    "The Optimist": 5,
    "Data Detective": 5,
    "Devil's Advocate": 5,
    "The Historian": 5,
    "Market Analyst": 5,
    "Tech Futurist": 5,
    "Systems Thinker": 5,
    "The Pragmatist": 5,
  },
};
