/*
  # Seed AI, Product Development & Startup Topics

  ## Summary
  Adds a large batch of high-quality, founder-focused topics to the agent_topics table.
  These replace the generalist coverage with topics specifically relevant to:
  - AI product strategy and LLM deployment
  - Product development and product-market fit
  - Startup operations, fundraising, and team building
  - Entrepreneurship and founder psychology

  ## New Topics (75 total across 5 domain categories)
  - ai_product: 20 topics on LLMs, AI agents, inference, AI UX, AI-native design
  - product_development: 20 topics on PMF, PLG, roadmaps, user research, retention
  - startup_ops: 15 topics on hiring, cap tables, fundraising, burn rate
  - entrepreneurship: 15 topics on founder mindset, pivoting, building in public
  - technology: 5 topics on developer tools, open source, technical decisions

  ## Notes
  - All topics set is_active=true, used=false so they enter rotation immediately
  - Existing topics are unaffected
*/

INSERT INTO agent_topics (title, description, domain, post_type, is_active, used) VALUES

-- AI PRODUCT (20 topics)
('Most AI Features Shipped in 2024 Will Be Deprecated Within 18 Months',
 'The first wave of AI feature integration — chatbots bolted onto existing products, GPT-4 wrappers with thin UI — is already showing churn and abandonment signals. The problem isn''t the technology; it''s that teams shipped AI features without rethinking the underlying job-to-be-done. Products built around model capabilities rather than user outcomes are structurally fragile.',
 'ai_product', 'opinion', true, false),

('RAG Is Being Misapplied by Almost Every Team That Uses It',
 'Retrieval-Augmented Generation has become the default architecture for enterprise AI products, but most implementations retrieve the wrong chunks, at the wrong granularity, with the wrong embedding models. The result is a product that looks impressive in demos and fails in production. The fix requires treating retrieval as a first-class product problem, not an engineering afterthought.',
 'ai_product', 'industry_problem', true, false),

('The Real Cost of Running LLMs in Production Is 10x What Founders Estimate',
 'Inference costs, context window fees, retry logic, guardrail layers, and evaluation infrastructure add up to a bill that most AI startup founders underestimate by an order of magnitude. The founders who build durable AI products treat inference cost as a product constraint from day one, not a scaling problem to solve later.',
 'ai_product', 'opinion', true, false),

('AI Agents Will Eat SaaS Workflows Faster Than Anyone Is Prepared For',
 'The shift from AI-assisted tasks to AI-autonomous workflows is closer than most SaaS founders think. When an agent can complete a multi-step workflow end-to-end — without human intervention — the value proposition of software-as-a-UI collapses. Founders building in SaaS categories need a clear answer to the question: what does our product look like when the user is an AI?',
 'ai_product', 'breakthrough_idea', true, false),

('Prompt Engineering Is a Product Skill, Not an Engineering Skill',
 'The teams shipping the best AI products have moved prompt ownership from engineers to product managers and domain experts. Engineering can build the pipeline; the people who understand user intent and edge cases write the prompts. Most startups have this backwards, which is why their AI features feel technically correct but practically useless.',
 'ai_product', 'opinion', true, false),

('Fine-Tuning Is Overused and Misunderstood by Most AI Startups',
 'Founders reach for fine-tuning when better prompt design, retrieval architecture, or model selection would solve the problem at a fraction of the cost and maintenance burden. Fine-tuning makes sense for specific, stable tasks with high data quality — not as a general solution to "make the model better at our use case."',
 'ai_product', 'industry_problem', true, false),

('AI-Native Products Need a New Design Language That Doesn''t Exist Yet',
 'Most AI products are designed as if they are traditional software with an AI module plugged in. The interaction patterns — text boxes, submit buttons, loading spinners — were designed for deterministic systems. AI outputs are probabilistic, iterative, and contextual, and the products that will win are those that design for that reality from the ground up.',
 'ai_product', 'breakthrough_idea', true, false),

('The Moat in AI Products Is Not the Model — It''s the Data Flywheel',
 'Any product built on top of a foundation model can be replicated in weeks by a competitor using the same model. The durable competitive advantage comes from proprietary data generated by users that improves outputs over time. Founders who understand this build products that get smarter as they scale; those who don''t build commodities.',
 'ai_product', 'opinion', true, false),

('Multimodal AI Is Creating Product Categories That Didn''t Exist 12 Months Ago',
 'The combination of vision, audio, and text in a single inference call has moved from research curiosity to production-ready capability in under a year. Founders who map their domain problems to multimodal inputs — field inspection, customer calls, document processing — are finding entirely new product wedges that legacy software vendors are structurally unable to address.',
 'ai_product', 'breakthrough_idea', true, false),

('AI Evaluation Is the Unsolved Product Problem Every Team Is Ignoring',
 'Shipping an AI feature without a rigorous evaluation framework is like shipping software without tests. The problem is that most teams don''t know what good looks like for their specific use case, so they rely on vibes and user complaints to detect regressions. Building an eval suite is unglamorous work that dramatically reduces the cost of iteration.',
 'ai_product', 'industry_problem', true, false),

('The Best AI Product Teams Are Running 10x More Experiments Than Traditional Product Teams',
 'The speed of model capability improvement means that experiments that failed six months ago may succeed today. AI product teams that treat model selection, prompt architecture, and retrieval strategy as dynamic variables — and run structured experiments against them — compound learning far faster than teams that pick a stack and stick with it.',
 'ai_product', 'opinion', true, false),

('Context Windows Are Getting So Large They Break Traditional Product Architecture',
 'When a model can ingest an entire codebase, a year of customer conversations, or a company''s full documentation in a single call, the product logic built around chunking, summarisation, and retrieval needs to be fundamentally reconsidered. The architectures being built today will need significant rethinking as 1M+ token contexts become standard.',
 'ai_product', 'breakthrough_idea', true, false),

('AI Copilots Are Failing Because They Interrupt Rather Than Assist',
 'The dominant AI copilot pattern — suggest, interrupt, ask for confirmation — creates cognitive overhead that erases the productivity gains. The next generation of AI assistance will be ambient: acting on the user''s behalf in the background and surfacing results, not demanding attention mid-task. Products that get this right will have dramatically higher retention.',
 'ai_product', 'industry_problem', true, false),

('Vertical AI Products Are Beating Horizontal AI Platforms on Every Metric That Matters',
 'Narrow AI products built for a specific workflow in a specific industry — legal contract review, medical coding, logistics dispatch — are outperforming general-purpose AI tools on retention, NPS, and willingness to pay. The reason is domain-specific data, domain-specific evaluation, and domain-specific trust-building that horizontal platforms cannot replicate.',
 'ai_product', 'opinion', true, false),

('Building on OpenAI API Is a Strategic Risk Most Startups Are Not Pricing In',
 'Dependency on a single API provider creates pricing risk, availability risk, and competitive risk — OpenAI has already entered categories occupied by startups building on its own API. The founders who are thinking clearly about this are building model-agnostic abstraction layers and testing fallback providers before they need them.',
 'ai_product', 'opinion', true, false),

('AI Product Metrics Need to Be Fundamentally Different From Traditional SaaS Metrics',
 'DAU, session length, and feature adoption are the wrong primary metrics for AI products. The metrics that matter are task completion rate, AI-assisted vs unassisted outcomes, error recovery rate, and the delta in user output quality. Most teams are measuring activity instead of value delivered, which leads them to optimise for engagement over outcomes.',
 'ai_product', 'breakthrough_idea', true, false),

('The Hidden Cost of AI in B2B Products Is Trust, Not Technology',
 'Enterprise buyers do not resist AI because of capability gaps — they resist it because they cannot explain AI decisions to their compliance teams, customers, or regulators. The startups winning enterprise AI deals are those who have invested in explainability, audit trails, and human-in-the-loop override mechanisms, not the ones with the highest benchmark scores.',
 'ai_product', 'industry_problem', true, false),

('Structured Output from LLMs Is the Unlock Most Product Teams Are Missing',
 'Most products using LLMs treat them as text generators, but the highest-leverage use case is structured data extraction — converting unstructured inputs into typed, validated, machine-readable outputs. This pattern unlocks automation workflows that are impossible with free-form text and makes LLM outputs composable with the rest of a software stack.',
 'ai_product', 'breakthrough_idea', true, false),

('AI Will Commoditise Every Software Category Except the Ones With Network Effects',
 'When building a new software product becomes 10x faster, the cost of replication falls to near zero. The only defensible software businesses in an AI-saturated market are those whose value comes from the network — data network effects, user network effects, or integration network effects. Everything else becomes a feature, not a product.',
 'ai_product', 'opinion', true, false),

('Most AI Startups Are Solving the Demo Problem, Not the Production Problem',
 'LLMs are extraordinarily good at producing compelling outputs in controlled conditions. The production problem — consistency, latency, cost, safety, and failure recovery at scale — is a fundamentally different engineering and product challenge that most AI startups discover six months after launch. The teams that win are those who treat production constraints as design requirements from day one.',
 'ai_product', 'industry_problem', true, false),

-- PRODUCT DEVELOPMENT (20 topics)
('Product-Market Fit Is a Feeling Founders Misidentify Constantly',
 'Most founders declare PMF when retention improves or revenue grows, but these are lagging indicators that can reflect novelty effects, strong sales, or a niche that does not scale. True PMF is when customers pull the product into new use cases you did not design for, refer unprompted, and resist churning even when cheaper alternatives exist.',
 'product_development', 'opinion', true, false),

('The Discovery Phase Is Being Cut Short at Every Startup That Is Struggling',
 'Founders who move from idea to build in under four weeks consistently skip the qualitative research that would have told them what job customers actually needed done. The pressure to ship is real, but the cost of building the wrong thing is always higher than the cost of an extra two weeks of discovery. Most failed products were technically well-built solutions to the wrong problem.',
 'product_development', 'industry_problem', true, false),

('Product-Led Growth Only Works If Your Product Has a Natural Viral Loop',
 'PLG has become the default go-to-market for SaaS startups, but the model only works if the product creates natural sharing moments — collaboration features, outputs that get sent to non-users, or network effects. Bolting PLG mechanics onto a single-player tool does not create growth; it creates a free tier that burns money without converting.',
 'product_development', 'opinion', true, false),

('User Onboarding Is the Highest-Leverage Engineering Investment a Startup Can Make',
 'A ten percent improvement in activation rate compounds across every cohort for the life of the product. Yet most startups treat onboarding as a design problem to be solved once at launch rather than a product surface to be iterated continuously. The teams with the best retention curves are those who have run hundreds of onboarding experiments.',
 'product_development', 'breakthrough_idea', true, false),

('The North Star Metric Framework Is Being Used to Optimise the Wrong Thing',
 'North star metrics work when they are genuine proxies for customer value — but most startups pick metrics that are easy to move rather than meaningful to measure. Engagement metrics that can be inflated by notifications, dark patterns, or artificial friction are common examples. The right north star metric makes your best customers happy and your worst customers churn.',
 'product_development', 'opinion', true, false),

('B2B Products Are Designed for Buyers, Not Users — and That Is Why They Fail',
 'The person who signs the contract is rarely the person who uses the product daily. B2B products optimised for the buyer — impressive demos, feature lists, compliance checklists — consistently underperform on user adoption and renewal. The products with the highest net revenue retention are those that obsess over the daily experience of the end user, not the quarterly review with the economic buyer.',
 'product_development', 'industry_problem', true, false),

('Jobs-to-Be-Done Is the Most Useful Product Framework That Most Teams Apply Wrong',
 'JTBD is not a user research method — it is a way of understanding causality in product adoption. Most teams use it to generate feature ideas rather than to understand the conditions under which customers switch. The teams that apply it correctly discover that customers hire their product not for its features but to avoid a specific anxiety, social risk, or operational pain.',
 'product_development', 'opinion', true, false),

('Shipping Faster Is Not the Same as Learning Faster',
 'Velocity culture has led many product teams to ship constantly without building the measurement infrastructure to know what is working. A team that ships ten features a month with no instrumentation learns less than a team that ships two features with rigorous A/B tests, retention tracking, and qualitative follow-up. Speed of learning, not speed of shipping, is the relevant metric.',
 'product_development', 'opinion', true, false),

('Churn Analysis Is the Most Neglected Product Practice at Growth-Stage Startups',
 'Most startups track churn as a number but do not investigate it as a signal. Exit interviews are rare, churn cohort analysis is rarer, and systematic categorisation of churn reasons is almost nonexistent. Every churned customer is a complete theory of your product''s failure that you have not read.',
 'product_development', 'industry_problem', true, false),

('Roadmap Prioritisation Frameworks Are Hiding Poor Product Judgment',
 'RICE, ICE, and similar scoring frameworks create the appearance of rigorous decision-making while actually encoding the assumptions of whoever sets the weights. They are useful for communicating decisions, not for making them. The best product managers treat prioritisation frameworks as accountability tools, not decision-making tools — the judgment comes first.',
 'product_development', 'opinion', true, false),

('The Activation Metric Is More Important Than the Acquisition Metric at Seed Stage',
 'Most seed-stage teams measure success by top-of-funnel growth — signups, downloads, waitlist joins — because these are easy to move with marketing spend. The activation rate, which measures how many acquired users reach the aha moment, is a far better predictor of whether a business will work. A startup that converts 5% of signups to activated users has a product problem, not a marketing problem.',
 'product_development', 'breakthrough_idea', true, false),

('Qualitative Research Scales Better Than Most Product Teams Think',
 'The assumption that qualitative user research stops being useful at scale is wrong. At any company size, five to eight user interviews per week with the right customers surface more actionable insight than dashboards. The teams that maintain a live qualitative research practice alongside their quantitative instrumentation consistently make better product decisions.',
 'product_development', 'opinion', true, false),

('Feature Flags Are Infrastructure That Every Startup Should Build in Year One',
 'Feature flags enable safe deployment, targeted rollouts, A/B testing, and instant kill switches for production issues. Teams that ship without them accumulate deployment risk with every release. The upfront investment is small; the cost of retrofitting flag infrastructure into a messy production system is enormous.',
 'product_development', 'breakthrough_idea', true, false),

('Design Systems Pay Back Their Investment Faster Than Any Other Technical Investment',
 'Founders delay building design systems because they feel like overhead at small scale. In practice, a lightweight design system at 10 engineers saves more cumulative time and produces more consistent user experiences than it costs at every stage of growth. The teams that build them early ship faster and with less design debt than those who don''t.',
 'product_development', 'breakthrough_idea', true, false),

('API-First Product Strategy Is the Most Defensible Go-to-Market for Developer Tools',
 'Developer tool companies that launch API-first — making the core value programmatically accessible before building a UI — accumulate production integrations that create switching costs before competitors can respond. The UI becomes a showcase, not a moat; the API and its ecosystem become the actual product.',
 'product_development', 'breakthrough_idea', true, false),

('Most Startups Mistake Engagement for Value',
 'Time-on-platform, session depth, and notification open rates measure engagement — not value delivered. Products that create genuine value often have low engagement by design: a tool that completes a task in 30 seconds is better than one that takes 10 minutes, even though the second logs more activity. Optimising for engagement in categories where value means speed leads to actively worse products.',
 'product_development', 'opinion', true, false),

('The Product Manager Role Is Poorly Defined at Most Early-Stage Startups',
 'At startups under 20 people, a PM who owns the roadmap, writes specs, and runs standups is often the bottleneck rather than the accelerant. The highest-value version of the role at early stage is customer obsession and hypothesis generation — not process management. Most early-stage founders hire a PM to add process when they should be hiring for customer insight.',
 'product_development', 'industry_problem', true, false),

('Retention Cohort Analysis Is the Most Honest Signal About Whether a Product Works',
 'Revenue growth, user growth, and NPS can all look healthy while a product is failing. Retention cohorts tell the truth: if the percentage of users still active at week 12 is the same as week 1, the product has no retention problem; if it drops to near zero, no amount of acquisition spend will build a durable business. Every founder should be able to draw their retention curve from memory.',
 'product_development', 'opinion', true, false),

('Pricing Is the Most Undertested Lever in Most Product Strategies',
 'Most startups set pricing once at launch based on competitor benchmarks and founder instinct, then leave it unchanged for years. Systematic pricing experiments — different tiers, packaging, anchoring, and willingness-to-pay research — consistently reveal that customers will pay significantly more for differently packaged value. Pricing is a product decision, not a sales decision.',
 'product_development', 'breakthrough_idea', true, false),

('The Best Product Teams Kill More Features Than They Ship',
 'Feature accumulation is the silent killer of product quality. Every feature adds interface complexity, maintenance burden, and cognitive load for users. The teams with the clearest, most loved products have explicit processes for deprecating features that are used by few, loved by fewer, and maintained by many. Subtraction is a product strategy.',
 'product_development', 'opinion', true, false),

-- STARTUP OPS (15 topics)
('Most Startup Cap Tables Are Broken Before Series A',
 'Founders who give away too much equity too early — to advisors, early employees, or seed investors with aggressive ownership targets — arrive at Series A with cap tables that signal poor judgment to lead investors and leave insufficient option pool for the team that will actually scale the company. The damage is largely irreversible without expensive and relationship-straining restructuring.',
 'startup_ops', 'industry_problem', true, false),

('The First Ten Hires Determine the Culture You Will Have at 100 Employees',
 'Culture is not a values document or an all-hands slide. It is the aggregate of the hiring decisions, conflict resolutions, and promotions that happen in the first two years. Founders who are explicit about the behaviours they are selecting for in the first ten hires set a cultural baseline that compounds; those who hire purely for skills and move fast create a culture by accident.',
 'startup_ops', 'opinion', true, false),

('Fundraising Takes Three Times Longer Than Founders Budget For',
 'The median time from first LP or VC meeting to cash in the bank is 90-120 days, not the 30-45 days most first-time founders assume. The founders who run out of runway during a fundraise almost always started the process too late and underestimated the number of meetings required to find conviction. Start raising at 8 months of runway, not 4.',
 'startup_ops', 'opinion', true, false),

('SAFE Notes Are Not As Founder-Friendly As the Ecosystem Pretends',
 'The SAFE has become the default seed instrument, but its simplicity obscures significant complexity around pro-rata rights, MFN clauses, and valuation cap dynamics that can result in severe dilution at Series A. Founders who sign SAFEs without modelling conversion scenarios on a live cap table frequently discover the real cost at the worst possible moment.',
 'startup_ops', 'industry_problem', true, false),

('The Biggest Risk in Early-Stage Hiring Is Hiring for the Wrong Stage',
 'Executives who have only worked in companies of 500 or more people consistently underperform at companies of 20. The skills, autonomy tolerance, and operational style required to build from scratch are fundamentally different from those required to manage scale. The most expensive hiring mistake an early-stage founder makes is bringing in a Head of Sales or VP Engineering who needs infrastructure that does not exist yet.',
 'startup_ops', 'opinion', true, false),

('Board Management Is a Skill Founders Are Never Taught and Desperately Need',
 'The relationship between a founder and their board determines how much operational autonomy the founder retains as the company scales. Founders who treat board meetings as reporting events rather than governance relationships consistently find themselves surprised when the board acts in ways that feel like betrayal but are actually predictable consequences of poor relationship management.',
 'startup_ops', 'industry_problem', true, false),

('Investor Updates Are the Highest-ROI Activity a Founder Does Each Month',
 'A well-crafted monthly investor update generates warm introductions, candidate referrals, customer leads, and strategic advice at near-zero cost. Founders who treat investor updates as compliance obligations miss the compounding value of keeping 20 well-connected people deeply informed about a problem they are invested in helping you solve.',
 'startup_ops', 'breakthrough_idea', true, false),

('Most Startups Hire a Head of Sales Before They Have a Repeatable Sales Process',
 'A sales leader hired before the founder has personally closed 20 to 30 customers in a consistent pattern will spend most of their time trying to figure out what works rather than scaling what works. The result is a burn rate that is three to five times higher than necessary and a sales motion that is no more defined at month 12 than it was at month one.',
 'startup_ops', 'opinion', true, false),

('Unit Economics Need to Be Understood at Pre-Seed, Not Series A',
 'Founders who defer unit economics modelling until they have "enough data" consistently arrive at Series A with business models that don''t work at scale. Understanding LTV:CAC ratio, payback period, and gross margin structure from the first 10 customers gives founders the information they need to make product, pricing, and channel decisions that compound correctly.',
 'startup_ops', 'breakthrough_idea', true, false),

('Remote-First Startups Have a Culture Debt Problem No One Is Measuring',
 'Distributed teams accumulate invisible alignment debt — diverging assumptions about priorities, working styles, and values — that compounds until a critical moment reveals it. Remote-first does not mean culture is less important; it means culture requires more deliberate investment in rituals, documentation, and synchronous time than co-located teams need.',
 'startup_ops', 'industry_problem', true, false),

('Equity Compensation Is Broken for Early Employees at Most Startups',
 'The combination of 4-year vesting, 90-day exercise windows, and strike prices set at 409A valuations that lag market means that most early employees either cannot afford to exercise their options or lose them when they leave. The founders who attract and retain the best early talent are those who offer extended exercise windows and are transparent about what equity is actually worth.',
 'startup_ops', 'industry_problem', true, false),

('The Fastest Path to Product-Market Fit Is Selling Before Building',
 'The founders who find PMF fastest are those who close five paying customers on a product that does not fully exist yet. Paid commitment signals genuine demand in a way that user interviews and free pilots cannot. Building begins with a clear understanding of what the first paying customers actually need, not what the founder imagines they need.',
 'startup_ops', 'breakthrough_idea', true, false),

('Burn Rate Is Not a Fixed Number — It Is a Strategic Choice',
 'Most founders treat their burn rate as a given — the cost of operating the team they have. The founders who navigate downturns and runway crunches best treat burn as an active lever: which experiments are worth the monthly cost, which headcount is load-bearing, and what is the minimum viable team to answer the next key question. Intentional burn management is a competitive advantage.',
 'startup_ops', 'opinion', true, false),

('Reference Checks Are Being Done in the Wrong Direction at Most Startups',
 'Founders reference-check candidates but rarely check references on investors, advisors, or executive hires in the direction that matters most: talking to people who reported to them, not people they chose to list. The most important reference for a VP candidate is a direct report who left voluntarily; the most important reference for an investor is a founder they backed who struggled.',
 'startup_ops', 'breakthrough_idea', true, false),

('Operating Cadence Is the Infrastructure of Startup Execution',
 'The startups that execute consistently are not those with the smartest founders or the best strategies — they are those with reliable operating cadences: weekly reviews where the right metrics are examined, clear decision rights, and a culture where bad news travels fast. Cadence is infrastructure for decision-making; without it, even good strategies fail through inconsistent execution.',
 'startup_ops', 'opinion', true, false),

-- ENTREPRENEURSHIP (15 topics)
('Most Startup Advice Is Written for a Market That No Longer Exists',
 'The canonical startup playbook — raise venture, hire fast, grow at all costs — was optimised for a zero-interest-rate environment with abundant capital, cheap customer acquisition, and patient public markets. The founders reading that playbook in 2025 are following directions to a destination that has moved. The strategies that work now are more capital-efficient, more focused, and more deliberate about unit economics from day one.',
 'entrepreneurship', 'opinion', true, false),

('Bootstrapping Is Underrepresented in Startup Media Because It Does Not Produce Press Releases',
 'The default narrative of successful startups is VC-backed, hypergrowth, and exit. The majority of durable, profitable software businesses are bootstrapped, slow-growing, and private — and they never appear in TechCrunch or Product Hunt. Founders who benchmark themselves against the fundraising narrative rather than the bootstrapped reality systematically overestimate how much capital they need and underestimate how much revenue they can generate.',
 'entrepreneurship', 'opinion', true, false),

('Founder-Market Fit Matters More Than Product-Market Fit in the First Year',
 'A great product in the hands of a founder who does not understand their market, lacks credibility with customers, or cannot endure the specific rejections of that industry will fail regardless of product quality. The question "why are you the right person to solve this problem?" has a more important answer than "is this a good product?" in the first 12 months.',
 'entrepreneurship', 'opinion', true, false),

('The Pivot Is Glorified Beyond What the Evidence Supports',
 'Startup culture has romanticised the pivot as a sign of intelligence and adaptability. In practice, most successful pivots are small — a different customer segment, a different pricing model, a different distribution channel — not wholesale reinventions of the business. Founders who pivot the core thesis more than once in the first two years are usually avoiding the harder work of making the original idea work.',
 'entrepreneurship', 'opinion', true, false),

('Building in Public Works Differently Than Founders Think',
 'Building in public is widely understood as a growth tactic — posting milestones, revenue numbers, and lessons learned to build an audience. The more valuable function is forcing clarity: when you have to explain your progress weekly to an audience that does not know your business, you discover which assumptions are genuinely held and which are wishful thinking. The audience is a side effect; the discipline is the product.',
 'entrepreneurship', 'breakthrough_idea', true, false),

('Co-Founder Conflicts Are the Leading Preventable Cause of Early Startup Failure',
 'Most co-founder breakups are predictable from the dynamics present at founding: unclear equity splits, undefined roles, different risk tolerances, and no agreed process for resolving disagreements. The founders who last are those who have the uncomfortable conversations about money, control, and exit expectations before there is enough at stake to make those conversations feel threatening.',
 'entrepreneurship', 'industry_problem', true, false),

('The Hardest Part of Being a Founder Is Not the Work — It Is the Uncertainty',
 'Technical challenges, customer acquisition, and team management are hard but learnable. The psychological experience of sustained uncertainty — not knowing if the product will work, if the money will come, if the team will stay — is the part that no amount of preparation fully addresses. Founders who build practices for managing uncertainty outperform those who rely on conviction alone.',
 'entrepreneurship', 'opinion', true, false),

('Niche Dominance Is a Better Early Strategy Than Broad Market Capture',
 'The founders who win large markets almost always start by completely dominating a small, specific segment. The mistake of going broad too early — trying to serve five customer types with one product — consistently produces a product that is mediocre for everyone rather than essential for someone. The path to category leadership runs through niche dominance.',
 'entrepreneurship', 'opinion', true, false),

('Fundraising Optimised for Valuation Usually Produces the Wrong Investors',
 'Founders who optimise their seed round for the highest valuation often end up with investors who have the least relevant networks, the most aggressive governance preferences, and the least patience for the learning periods that all early-stage companies require. The round that maximises option value is the one with the investors who will be most useful in the next 18 months, regardless of headline valuation.',
 'entrepreneurship', 'opinion', true, false),

('The Competitive Moat for Solo Founders Is Speed, Not Resources',
 'Solo founders cannot out-resource a funded competitor, but they can out-iterate one. The competitive advantage of a single decision-maker who ships, measures, and adjusts without committee is speed of learning. Solo founders who waste their structural advantage by trying to build like a team — roadmap planning, sprint ceremonies, consensus processes — are competing on the wrong dimension.',
 'entrepreneurship', 'breakthrough_idea', true, false),

('Second-Time Founders Fail in Predictable Ways That First-Time Founders Don''t',
 'The pattern-matching that makes second-time founders valuable — knowing what Series A metrics look like, how to hire senior leaders, how to run a board — becomes a liability when applied to a market or model that does not match the previous experience. Second-time founders consistently overbuild, overhire, and over-process too early, because they are solving the problems they had last time, not the problems they have now.',
 'entrepreneurship', 'opinion', true, false),

('The Best Time to Expand Your Market Is When You Own a Niche, Not Before',
 'Premature market expansion — broadening the ICP before the core segment is thoroughly owned — is one of the most common causes of growth stalls at Series A and B. Investors celebrate TAM expansion; experienced operators know it dilutes focus before the company has earned the right to expand. The discipline to say no to adjacent opportunities is a competitive advantage.',
 'entrepreneurship', 'opinion', true, false),

('Founder Energy Is a Resource That Most Operating Plans Do Not Account For',
 'Startup operating models plan headcount, capital, and time — but not the cognitive and emotional energy of the founder. Founders who run unsustainable sprints for extended periods make progressively worse decisions, retain teams poorly, and often burn out at exactly the moment their company needs them most. Energy management is a strategic input, not a lifestyle preference.',
 'entrepreneurship', 'industry_problem', true, false),

('The Minimum Viable Product Has Been Misunderstood for a Decade',
 'The MVP is not the simplest version of your product you can build — it is the smallest experiment that can test your most critical assumption. Most teams build MVPs that are feature-minimal versions of their full vision rather than experiments designed to generate specific evidence. The result is a product that took three months to build and still does not answer the question that determines whether the business works.',
 'entrepreneurship', 'opinion', true, false),

('Community-Led Growth Is the Most Capital-Efficient Distribution Strategy No One Is Executing Well',
 'Building a community of practitioners around a problem — not a product — creates distribution, feedback loops, and brand credibility that paid acquisition cannot replicate at any budget. The founders who do it well treat community as a product with its own metrics, not a marketing channel with a Slack workspace. It requires patience and a fundamentally different creative investment than growth hacking.',
 'entrepreneurship', 'breakthrough_idea', true, false),

-- TECHNOLOGY (5 topics)
('Open Source Is the Best Go-to-Market Strategy for Developer Tools That Most Founders Underuse',
 'Developer tools that launch as open source projects build production usage, GitHub stars, and community trust before a commercial offering exists. The companies that have successfully commercialised open source — dbt, Supabase, Posthog — used community as their primary distribution channel and enterprise as their monetisation layer. This playbook is well-documented and still dramatically underused.',
 'technology', 'breakthrough_idea', true, false),

('Technical Debt Is a Management Problem, Not an Engineering Problem',
 'Technical debt accumulates when product pressure consistently overrides engineering judgment on quality trade-offs. It is not caused by bad engineers — it is caused by management systems that do not make the cost of debt visible until it slows velocity catastrophically. Founders who track technical debt as a balance sheet item and allocate explicit capacity to it have dramatically better engineering efficiency at scale.',
 'technology', 'industry_problem', true, false),

('The Engineering Interview Process Is Selecting for the Wrong Skills',
 'Algorithm puzzles and data structure challenges test skills that are almost never used in production software development. The best engineers at building products — who communicate clearly, debug production issues under pressure, make good architectural decisions with incomplete information — are systematically filtered out by hiring processes designed for Big Tech, not startups.',
 'technology', 'opinion', true, false),

('Developer Experience Is a Product Problem That Most Startups Treat as Documentation',
 'DX is the sum of all friction a developer encounters integrating with your API, SDK, or platform. Startups that invest in DX — clear error messages, good defaults, fast time-to-hello-world — acquire and retain developer customers at a fraction of the sales cost of those that rely on documentation and support tickets. DX is a product investment with measurable CAC and retention returns.',
 'technology', 'breakthrough_idea', true, false),

('Cloud Costs Are the Invisible CAC of AI Products',
 'In traditional SaaS, the variable cost of serving a customer is near zero. In AI products, every request has a meaningful compute cost that scales with usage. Founders who do not model compute cost per customer as part of their unit economics end up with a product that is economically unviable at scale even when customers love it. Cloud cost architecture is a product decision that needs to happen before the first user, not after.',
 'technology', 'opinion', true, false);
