
-- The source_area constraint was too restrictive — it only allowed internal synthesis
-- category labels (risk, blind_spot, etc.) but the AI generates business function owners
-- (CEO, CFO, HR, etc.). Every AI action item insert was silently rejected.
-- Drop the old constraint and replace it with one that covers both use cases.

ALTER TABLE workspace_action_items
  DROP CONSTRAINT workspace_action_items_source_area_check;

ALTER TABLE workspace_action_items
  ADD CONSTRAINT workspace_action_items_source_area_check
  CHECK (source_area = ANY (ARRAY[
    -- Legacy synthesis-category values
    'risk', 'blind_spot', 'open_question', 'conflict', 'manual',
    -- Business-function owner values generated by the AI synthesis
    'CEO', 'CFO', 'HR', 'Legal', 'Product', 'Engineering',
    'Finance', 'Risk', 'Strategy', 'Marketing', 'Operations', 'People'
  ]));

-- Now backfill action items from the synthesis JSON for workspaces that
-- currently have no AI-generated rows in this table.
INSERT INTO workspace_action_items (
  workspace_id,
  text,
  source,
  priority,
  source_area,
  status,
  created_by
)
SELECT
  ws.workspace_id,
  trim((item->>'text')::text) AS text,
  'ai' AS source,
  CASE
    WHEN (item->>'priority') IN ('critical','high','medium','low') THEN (item->>'priority')
    ELSE 'medium'
  END AS priority,
  CASE
    WHEN (item->>'source_area') IN (
      'risk','blind_spot','open_question','conflict','manual',
      'CEO','CFO','HR','Legal','Product','Engineering',
      'Finance','Risk','Strategy','Marketing','Operations','People'
    ) THEN (item->>'source_area')
    ELSE 'Strategy'
  END AS source_area,
  'todo' AS status,
  NULL AS created_by
FROM workspace_synthesis ws,
  jsonb_array_elements(ws.action_items::jsonb) AS item
WHERE
  jsonb_array_length(ws.action_items::jsonb) > 0
  AND (item->>'text') IS NOT NULL
  AND length(trim(item->>'text')) > 5
  AND NOT EXISTS (
    SELECT 1 FROM workspace_action_items wai
    WHERE wai.workspace_id = ws.workspace_id
      AND wai.source = 'ai'
  );
